defmodule Lux.Prisms.YouTube.ReportGeneratorPrism do
  @moduledoc """
  A prism that compiles analytics and predictions into an automated report.
  """

  use Lux.Prism,
    name: "YouTube Report Generator",
    description: "Generates an automated analytics report",
    input_schema: %{
      type: :object,
      properties: %{
        channel_name: %{type: :string},
        stats: %{
          type: :object,
          properties: %{
            views: %{type: :integer},
            subscribers: %{type: :integer},
            videos: %{type: :integer}
          }
        },
        predicted_subscribers: %{type: :integer},
        estimated_revenue_usd: %{type: :number}
      },
      required: ["channel_name", "stats"]
    },
    output_schema: %{
      type: :object,
      properties: %{
        report_markdown: %{
          type: :string,
          description: "Generated report in Markdown format"
        }
      },
      required: ["report_markdown"]
    }

  def handler(input, _ctx) do
    name = Map.get(input, :channel_name, "Channel")
    stats = Map.get(input, :stats, %{})
    predicted = Map.get(input, :predicted_subscribers, "N/A")
    revenue = Map.get(input, :estimated_revenue_usd, "N/A")

    report = """
    # YouTube Analytics Report: #{name}

    ## Current Statistics
    - **Subscribers**: #{Map.get(stats, :subscribers, "N/A")}
    - **Total Views**: #{Map.get(stats, :views, "N/A")}
    - **Total Videos**: #{Map.get(stats, :videos, "N/A")}

    ## Growth Projections
    - **Predicted Subscribers (12 months)**: #{predicted}

    ## Revenue Estimates
    - **Estimated Revenue**: $#{revenue}

    *Generated by Lux YouTube Analytics Engine*
    """

    {:ok, %{report_markdown: report}}
  end
end
